### PR TITLE
Cleanup migrations

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by ticosax** [comment]
let's make sure we all ran migration on our dev instance first
- [x] @ticosax
- [x] @pkolios

**Comment by blueyed** [comment]
As for me merging master broke it already: 28a3baf

> Migration pinax_stripe.0023_merge_20171027_1626 dependencies reference nonexistent parent node ('pinax_stripe', '0013_auto_20171027_1443')

How does it look for you?  via `manage.py showmigrations`

**Comment by ticosax** [comment]
on this branch, all migrations seems to be applied and `showmigrations` just works.

**Comment by blueyed** [comment]
On this branch I get:

> Migration lock8.0025_organization-account depends on nonexistent node ('pinax_stripe', '0012_user_account')

Fixed by:

```diff
diff --git i/velodrome/lock8/migrations/0025_organization-account.py w/velodrome/lock8/migrat
index c51ba246..027cb375 100644
--- i/velodrome/lock8/migrations/0025_organization-account.py
+++ w/velodrome/lock8/migrations/0025_organization-account.py
@@ -9,7 +9,7 @@
 class Migration(migrations.Migration):
 
     dependencies = [
-        ('pinax_stripe', '0012_user_account'),
+        ('pinax_stripe', '0010_connect_squashed_0026_merge_20171106_2259'),
         ('lock8', '0024_organizationpreference_uses_payments'),
     ]
 ```

showmigrations for pinax_stripe:
```
pinax_stripe
 [X] 0001_initial
 [X] 0002_auto_20151205_1451
 [X] 0003_make_cvc_check_blankable
 [X] 0004_plan_metadata
 [X] 0005_auto_20161006_1445
 [X] 0006_coupon
 [X] 0007_auto_20170108_1202
 [X] 0008_auto_20170509_1736
 [X] 0009_auto_20170825_1841
 [X] 0010_connect
 [X] 0011_subscription_connect
 [ ] 0011_rename_account_transfers_payout
```

After running migrations from this branch/PR:
```
pinax_stripe
 [X] 0001_initial
 [X] 0002_auto_20151205_1451
 [X] 0003_make_cvc_check_blankable
 [X] 0004_plan_metadata
 [X] 0005_auto_20161006_1445
 [X] 0006_coupon
 [X] 0007_auto_20170108_1202
 [X] 0008_auto_20170509_1736
 [X] 0009_auto_20170825_1841
 [X] 0010_connect
 [X] 0011_subscription_connect
 [X] 0011_rename_account_transfers_payout
```

Our squashed migration does not seem to be used anymore.

**Comment by blueyed** [comment]
> Our squashed migration does not seem to be used anymore.

But is required for Discount - so likely it is just not listed or something like that..

**Comment by pkolios** [comment]
No problems on my side. You can merge.

**Comment by blueyed** [comment]
Thanks.

**Pull request merged**
